apiVersion: v1
name: rke2-cilium-hard-defaults
description: Default options for cilium in RKE2
version: 1.0.0
home: https://docs.rke2.io/
keywords:
  - cilium
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
