operator:
  image:
    repository: rancher/hardened-sriov-network-operator
    tag: release-4.8

cni:
  image:
    repository: rancher/hardened-sriov-cni
    tag: v2.6

cni_infiniband:
  image:
    repository: quay.io/openshift/origin-sriov-infiniband-cni
    tag: 4.8.0

device_plugin:
  image:
    repository: rancher/hardened-sriov-network-device-plugin
    tag: v3.3.1

injector:
  image:
    repository: rancher/hardened-sriov-network-resources-injector
    tag: v1

config_daemon:
  image:
    repository: rancher/hardened-sriov-network-config-daemon
    tag: release-4.8

webhook:
  image:
    repository: rancher/hardened-sriov-network-resources-injector
    tag: v1

global:
  systemDefaultRegistry: ""
