multus:
  image:
    repository: rancher/hardened-multus-cni
    tag: v3.7.1-build20210416

cniplugins:
  image:
    repository: rancher/hardened-cni-plugins
    tag: v0.9.1-build20210414
  skipcnis: flannel

global:
  systemDefaultRegistry: ""
